#!/usr/bin/env zsh
source ${0:a:h}/../lib/query.zsh

description 'Get the benchmark for a fund'

argument fund 'portfolio name'

option date a 'benchmark date' $TODAY
option type s 'benchmark type' RISK
option order o 'benchmark order' 1

parse $0 $@

sql --list <<SQL
select bench.portfolio_name
from portdb.dbo.portfolios fund
inner join portdb.dbo.benchmarks bm
  on fund.portfolio_code = bm.portfolio_code
inner join portdb.dbo.portfolios bench
  on bm.bench_cusip = bench.cusip
where fund.portfolio_name = "$fund"
  and bm.entry_date <= "$date"
  and (bm.exit_date is null or bm.exit_date >= "$date")
  and bm.bench_type = "$type"
  and bm.bench_order = $order
go
SQL
