#!/usr/bin/env zsh
source ${0:a:h}/../lib/query.zsh

description 'Get FX rates'

argument pair 'currency pair'

option date a 'date' $YESTERDAY

parse $0 $@

if [[ $#pair == 3 ]]; then
  currency1=USD
elif [[ $#pair == 6 ]] || [[ $#pair == 7 ]]; then
  currency1=${(U)pair[-3,-1]}
else
  help
fi

currency2=${(U)pair[1,3]}

sql --list <<SQL
select ecb1.fxspot / ecb2.fxspot as fxspot
from economydb.dbo.econ_cswap_basis ecb1
inner join economydb.dbo.econ_cswap_basis ecb2
    on ecb1.date = ecb2.date
    and ecb1.purpose = ecb2.purpose
where ecb1.date = "$date"
    and ecb1.purpose = "P100"
    and ecb2.currency2 = "$currency2"
    and ecb1.currency2 = "$currency1"
go
SQL
