#!/usr/bin/env zsh
source ${0:a:h}/../lib/query.zsh

description "List a portfolio group's underlying funds"

argument group 'portfolio group'

parse $0 $@

sql --list <<SQL
select portfolio_name
from portdb.dbo.port_group_expand
where anc_port_group = "${(U)group}"
go
SQL
